# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad4a36b40da5b67c646a57d0e1b852502ab5374dfeb411e00540b5fa85f111502a08704a4e2e616fcd1a5e88d7dad35e504ce6513a2865ff1e8a0beae1fa8332

test:
  secret_key_base: 000797f8eade3444b2d66f6af5b0c45b3b4d3050133e7f5a86a9ba751ae00748dbc320d93b5ff95732d65678392790b051e15137b4f40758637425ad93d5589e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
